# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 272e136c538265c20c176e1d9412cafecb3e3a99a4dcbed4b8b0f228cdd14690f247f46969923962bfdd4e83fd9fc56a5716696966811a6fdfbe899614d7e0b7

test:
  secret_key_base: 806047710ee44bda38d3f77a93db0a90c4a698e1fb58289b025abb0a30c156b76519dac32d8ca76b96106691bdd11e6f784d1d4fec8f96034902f01998f7c5d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
